// <auto-generated />
using System;
using EurasianTest.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EurasianTest.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190902105744_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.ProjectAdministrator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<long>("ProjectId");

                    b.Property<DateTime?>("Updated");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectAdministrator");
                });

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<long>("ProjectId");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.TaskHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("NewStatus");

                    b.Property<long>("NewUserId");

                    b.Property<int>("OldStatus");

                    b.Property<long>("OldUserId");

                    b.Property<long>("TaskId");

                    b.Property<DateTime?>("Updated");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NewUserId");

                    b.HasIndex("OldUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskHistory");
                });

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Role");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.ProjectAdministrator", b =>
                {
                    b.HasOne("EurasianTest.DAL.Entities.Implementations.Project", "Project")
                        .WithMany("ProjectAdministrators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EurasianTest.DAL.Entities.Implementations.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.Task", b =>
                {
                    b.HasOne("EurasianTest.DAL.Entities.Implementations.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EurasianTest.DAL.Entities.Implementations.TaskHistory", b =>
                {
                    b.HasOne("EurasianTest.DAL.Entities.Implementations.User", "NewUser")
                        .WithMany("RecievedHistory")
                        .HasForeignKey("NewUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EurasianTest.DAL.Entities.Implementations.User", "OldUser")
                        .WithMany("SendedHistory")
                        .HasForeignKey("OldUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EurasianTest.DAL.Entities.Implementations.Task", "Task")
                        .WithMany("History")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EurasianTest.DAL.Entities.Implementations.User", "User")
                        .WithMany("History")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
